name: Deploy to Aliyun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/test-world/fullstack-demo:backend-${{ github.sha }} ./backend
          docker push ${{ secrets.ACR_REGISTRY }}/test-world/fullstack-demo:backend-${{ github.sha }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/test-world/fullstack-demo:frontend-${{ github.sha }} ./frontend
          docker push ${{ secrets.ACR_REGISTRY }}/test-world/fullstack-demo:frontend-${{ github.sha }}

      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/vote-app  # 进入你的项目部署目录
            docker login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_REGISTRY }}

            # 更新 docker-compose.yml 中的镜像标签
            sed -i "s|backend:.*|backend:${{ github.sha }}|" docker-compose.yml
            sed -i "s|frontend:.*|frontend:${{ github.sha }}|" docker-compose.yml

            docker compose pull
            docker compose up -d --force-recreate

            echo "Deployment successful!"
